name: RSP CI

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  

jobs:
  test:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        os: [ubuntu-latest]
        java: ["11"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java 17 for quickstarts
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Build & Verify using Maven
      run: mvn clean verify -Pintegration-tests -Dinvoker.javaHome=$JAVA_HOME_17_X64 -Dserver.vm.install.path=$JAVA_HOME_17_X64 -U -fae -e -B
    - name: Upload JaCoCo coverage reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-reports
        path: '**/target/site/jacoco/'
        retention-days: 14
